name: nyzo_wallet
description: An iOS and Android wallet for the Nyzo cryptocurrency.

publish_to: 'none'

version: 0.8.4+84

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Flutter widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0

  # Utilities for accessing binary data and bit manipulation in Dart and Flutter.
  binary:
    git:
      url: https://github.com/redDwarf03/binary.dart.git
      ref: master

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.1
  
  # Direct Select Widget Implementation inspired by https://dribbble.com/shots/3876250-DirectSelect-Dropdown-ux  
  direct_select_flutter: ^1.1.1

  # A set of high-level APIs over PointyCastle for two-way cryptography.
  encrypt: ^5.0.1

  # A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
  expandable: ^5.0.1
  
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter plugin picker. Include NumberPicker, DateTimePicker, ArrayPicker, and default linkage Picker. Provide flexible parameters to meet various needs.
  flutter_picker: ^2.0.2

  # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
  flutter_secure_storage: ^5.0.2

  # A Flutter implementation of slidable list item with directional slide actions that can be dismissed.
  flutter_slidable: ^1.1.0

  # A collection of loading indicators animated with flutter. Heavily inspired by @tobiasahlin's SpinKit.
  flutter_spinkit: ^5.1.0

  # Flutter icons from popular web icon fonts. Customize your final icon package using fluttericon.com.
  fluttericon: ^2.0.0

  # Easy hexadecimal convertion using dart:convert API.
  hex: ^0.2.0

  # APIs for parsing and manipulating HTML content outside the browser
  html: ^0.15.0

  # A small library for un-escaping HTML. Supports all Named Character References, Decimal Character References and Hexadecimal Character References.
  html_unescape: ^2.0.0

  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.13.4

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.17.0

  # A beautiful and custom refresh indicator with some cool animations and transitions for flutter.
  liquid_pull_to_refresh: ^3.0.0

  # Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
  local_auth: ^1.1.9

  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android
  package_info_plus: ^1.3.0

  # The Dart implementation of the PyNaCl APIs with the TweetNaCl cryptographic library
  pinenacl: ^0.3.3

  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter.
  qr_flutter: ^4.0.0

  # Plugin for reading QR codes using Firebase's Mobile Vision API.
  qr_mobile_vision: ^3.0.1

  # Reorderable table, row, column, wrap, sliver list that allow drag and drop of their children.
  reorderables: ^0.4.2

  # Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.0.11

  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^2.0.0

  # Dart implementation of sprintf. Provides simple printf like formatting such as sprintf("hello %s", ["world"]);
  sprintf: ^6.0.0

  # A beautiful, clean and simple bottom navigation bar with smooth animation on click. This package is high customizable, read more bellow for more details
  titled_navigation_bar: ^5.0.0-nullsafety.0

  # Tuple data structure
  tuple: ^2.0.0

  # Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS)
  uni_links: ^0.5.1

dev_dependencies:
  # Automatically organize your dart imports
  import_sorter: ^4.6.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
  assets:
    - images/Logo.png
    - images/noTransactions.png
    - images/noContacts.png
    - images/noVerifiers.png
    - images/qr.png
    - images/communicationProblem.png
    - images/normal.png
    - images/NotProducing.png
    - images/trackingProblem.png
    - images/cycle.png
    - images/nyzo-logo-white.png
    - images/bg-home-red-black.png
    - images/nytro-logo-black.png
    - images/nytro-logo-white.png

    - lang/en.json
    - lang/zh.json
    - lang/es.json
    - lang/nl.json
    - lang/de.json
    - lang/fr.json
    - lang/hr.json
    - lang/ru.json
    - lang/cs.json