name: nyzo_wallet
description: An iOS and Android wallet for the Nyzo cryptocurrency.

publish_to: 'none'

version: 0.8.0+80

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library
  pointycastle: ^3.3.1
  cupertino_icons: ^1.0.3
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.6
  string_encryption: ^2.0.3
  local_auth: ^1.1.6
  intl: ^0.17.0
  http: ^0.13.3
  pinenacl: ^0.3.3
  html: ^0.15.0
  crypto: ^3.0.1
  html_unescape: ^2.0.0
  vector_math: ^2.1.0
  titled_navigation_bar: ^5.0.0-nullsafety.0
  shimmer: ^2.0.0
  liquid_pull_to_refresh: ^3.0.0
  flutter_slidable: ^0.6.0
  expandable: ^5.0.1
  reorderables: ^0.4.1
  qr_flutter: ^4.0.0
  qr_mobile_vision: ^3.0.0
  flutter_picker: ^2.0.2
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  package_info: ^2.0.2
  direct_select_flutter: ^1.1.1
  flutter_spinkit: ^5.0.0
  hex: ^0.2.0

dev_dependencies:
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf

  assets:
    - images/Logo.png
    - images/noTransactions.png
    - images/noContacts.png
    - images/noVerifiers.png
    - images/qr.png
    - images/communicationProblem.png
    - images/normal.png
    - images/NotProducing.png
    - images/trackingProblem.png
    - images/cycle.png
    - images/nyzo-logo-white.png
    - images/bg-home-red-black.png

    - lang/en.json
    - lang/zh.json
    - lang/es.json
    - lang/nl.json
    - lang/de.json
    - lang/fr.json
    - lang/hr.json
    - lang/ru.json
    - lang/cs.json
    
