name: cryptography
version: 1.0.0
homepage: https://github.com/dint-dev/cryptography
description:
  Cryptographic algorithms for digital signature, key agreement, encryption, message authentication,
  and hashing. X25519, ED25519, AES, Chacha20, and many more.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  collection: ^1.10.0
  crypto: ^2.0.0
  js: ^0.6.0
  meta: ^1.1.0
  typed_data: ^1.1.0

dev_dependencies:
  benchmark_harness: ^1.0.0
  pedantic: ^1.9.0
  test: ^1.6.0
